# Copyright 2026 The ODML Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [Google-internal load of `cc_library`]
# [Google-internal load of `cc_test`]

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "text_source",
    hdrs = ["text_source.h"],
    deps = ["//omni/base:stage"],
)

cc_library(
    name = "text_frontend",
    hdrs = ["text_frontend.h"],
    deps = [
        ":text_source",
        "@com_google_absl//absl/base:nullability",
        "//omni/base:stage",
    ],
)

cc_library(
    name = "acoustic_predictor",
    hdrs = ["acoustic_predictor.h"],
    deps = [
        ":text_frontend",
        "@com_google_absl//absl/base:nullability",
        "//omni/base:stage",
    ],
)

cc_library(
    name = "latent_decoder",
    hdrs = ["latent_decoder.h"],
    deps = [
        ":acoustic_predictor",
        "@com_google_absl//absl/base:nullability",
        "//omni/base:stage",
    ],
)

cc_library(
    name = "vocoder",
    hdrs = ["vocoder.h"],
    deps = [
        ":latent_decoder",
        "@com_google_absl//absl/base:nullability",
        "@com_google_absl//absl/status",
        "//omni/base:stage",
    ],
)

cc_library(
    name = "tts_session",
    srcs = ["tts_session.cc"],
    hdrs = ["tts_session.h"],
    deps = [
        ":acoustic_predictor",
        ":latent_decoder",
        ":text_frontend",
        ":text_source",
        ":vocoder",
        "@com_google_absl//absl/base:core_headers",
        "@com_google_absl//absl/functional:any_invocable",
        "@com_google_absl//absl/log:absl_check",
        "@com_google_absl//absl/log:absl_log",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:status_macros",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/synchronization",
        "@com_google_absl//absl/time",
        "//omni/base:async_stage_scheduler",
        "//omni/base:stage",
        "//runtime/framework:threadpool",
    ],
)

cc_test(
    name = "tts_session_test",
    srcs = ["tts_session_test.cc"],
    deps = [
        ":acoustic_predictor",
        ":latent_decoder",
        ":text_frontend",
        ":text_source",
        ":tts_session",
        ":vocoder",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/base:nullability",
        "@com_google_absl//absl/cleanup",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/synchronization",
        "@litert//support/util:test_utils",
        "//omni/base:stage",
        "//runtime/framework:threadpool",
    ],
)
